openapi: 3.0.3
info:
  title: ERP API
  version: 1.0.0
  description: MÃ³dulo de pedidos.
paths:
  /api/v1/customers:
    get:
      operationId: api_v1_customers_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - api
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCustomerCreateList'
          description: ''
    post:
      operationId: api_v1_customers_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomerCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomerCreate'
        required: true
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerCreate'
          description: ''
  /api/v1/customers/{id}:
    get:
      operationId: api_v1_customers_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDetail'
          description: ''
  /api/v1/orders:
    get:
      operationId: api_v1_orders_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - api
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedOrderListList'
          description: ''
    post:
      operationId: api_v1_orders_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OrderCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OrderCreate'
        required: true
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderCreate'
          description: ''
  /api/v1/orders/{id}:
    get:
      operationId: api_v1_orders_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetail'
          description: ''
    delete:
      operationId: api_v1_orders_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/orders/{id}/status:
    patch:
      operationId: api_v1_orders_status_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedOrderStatusPatch'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedOrderStatusPatch'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedOrderStatusPatch'
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStatusPatch'
          description: ''
  /api/v1/products:
    get:
      operationId: api_v1_products_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - api
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProductCreateList'
          description: ''
    post:
      operationId: api_v1_products_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ProductCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProductCreate'
        required: true
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductCreate'
          description: ''
  /api/v1/products/{id}/stock:
    patch:
      operationId: api_v1_products_stock_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProductStockPatch'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProductStockPatch'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProductStockPatch'
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductStockPatch'
          description: ''
components:
  schemas:
    CustomerCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        cpf_cnpj:
          type: string
          maxLength: 20
        email:
          type: string
          format: email
          maxLength: 254
        phone:
          type: string
          maxLength: 50
        address:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - cpf_cnpj
      - created_at
      - email
      - id
      - name
    CustomerDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        cpf_cnpj:
          type: string
          maxLength: 20
        email:
          type: string
          format: email
          maxLength: 254
        phone:
          type: string
          maxLength: 50
        address:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - cpf_cnpj
      - created_at
      - email
      - id
      - name
      - updated_at
    Message:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    OrderCreate:
      type: object
      properties:
        customer_id:
          type: integer
          minimum: 1
        idempotency_key:
          type: string
          maxLength: 128
        observations:
          type: string
          default: ''
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderCreateItem'
      required:
      - customer_id
      - idempotency_key
      - items
    OrderCreateItem:
      type: object
      properties:
        product_id:
          type: integer
          minimum: 1
        qty:
          type: integer
          minimum: 1
      required:
      - product_id
      - qty
    OrderDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        number:
          type: string
          maxLength: 32
        created_at:
          type: string
          format: date-time
          readOnly: true
        customer_id:
          type: integer
        status:
          $ref: '#/components/schemas/OrderStatusEnum'
        total:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
        observations:
          type: string
        idempotency_key:
          type: string
          maxLength: 128
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemOut'
        status_history:
          type: array
          items:
            $ref: '#/components/schemas/OrderStatusHistory'
      required:
      - created_at
      - customer_id
      - id
      - idempotency_key
      - items
      - number
      - status_history
    OrderItemOut:
      type: object
      properties:
        product_id:
          type: integer
        qty:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
        unit_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
        subtotal:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
      required:
      - product_id
      - qty
      - subtotal
      - unit_price
    OrderList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        number:
          type: string
          maxLength: 32
        created_at:
          type: string
          format: date-time
          readOnly: true
        customer_id:
          type: integer
        status:
          $ref: '#/components/schemas/OrderStatusEnum'
        total:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
        observations:
          type: string
        idempotency_key:
          type: string
          maxLength: 128
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemOut'
        status_history:
          type: array
          items:
            $ref: '#/components/schemas/OrderStatusHistory'
      required:
      - created_at
      - customer_id
      - id
      - idempotency_key
      - items
      - number
      - status_history
    OrderStatusEnum:
      enum:
      - PENDENTE
      - CONFIRMADO
      - SEPARADO
      - ENVIADO
      - ENTREGUE
      - CANCELADO
      type: string
      description: |-
        * `PENDENTE` - PENDENTE
        * `CONFIRMADO` - CONFIRMADO
        * `SEPARADO` - SEPARADO
        * `ENVIADO` - ENVIADO
        * `ENTREGUE` - ENTREGUE
        * `CANCELADO` - CANCELADO
    OrderStatusHistory:
      type: object
      properties:
        from_status:
          $ref: '#/components/schemas/OrderStatusEnum'
        to_status:
          $ref: '#/components/schemas/OrderStatusEnum'
        changed_at:
          type: string
          format: date-time
        note:
          type: string
          maxLength: 255
      required:
      - from_status
      - to_status
    OrderStatusPatch:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/OrderStatusEnum'
        note:
          type: string
          default: ''
      required:
      - status
    PaginatedCustomerCreateList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/CustomerCreate'
    PaginatedOrderListList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/OrderList'
    PaginatedProductCreateList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/ProductCreate'
    PatchedOrderStatusPatch:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/OrderStatusEnum'
        note:
          type: string
          default: ''
    PatchedProductStockPatch:
      type: object
      properties:
        stock_qty:
          type: integer
          minimum: 0
    PatchedUserUpdate:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
        is_active:
          type: boolean
        profile:
          $ref: '#/components/schemas/ProfileEnum'
    ProductCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sku:
          type: string
          maxLength: 64
        name:
          type: string
          maxLength: 255
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
        stock_qty:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - name
      - price
      - sku
    ProductStockPatch:
      type: object
      properties:
        stock_qty:
          type: integer
          minimum: 0
      required:
      - stock_qty
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
